## 1. Inheritance

**Inheritance** is a mechanism in object-oriented programming that allows you to create a new class by deriving it from an existing class. The new class is called a subclass or derived class, and the existing class is called the superclass or base class. 

The subclass inherits:
1. All the properties of the superclass.
2. All the methods of the superclass.

It can also add its own properties and methods as well.

In [1]:
# Main Class
class Animal:  
    def __init__(self, name):
        self.name = name

    def speak(self):
        pass


# Sub-class 1 (Dog)
class Dog(Animal):
    def speak(self):
        return "Woof!"


# Sub-class 2 (Cat)
class Cat(Animal):
    def speak(self):
        return "Meow!"

my_dog = Dog("Rufus")
my_cat = Cat("Fluffy")

print(my_dog.speak()) # Output: Woof!
print(my_cat.speak()) # Output: Meow!

Woof!
Meow!


In Data Science, inheritance can be useful in several ways, such as Inheriting from a base class: <br>

_Example:_ <br>
You can define a base class that contains common functionality and then inherit from it to create specialized classes. <br>
For example, you could define a base class called "Classifier" that contains methods for training and evaluating a machine learning model, and then inherit from it to create specific classifiers like "RandomForestClassifier" or "LogisticRegressionClassifier".

https://www.educative.io/answers/what-is-class-inheritance-in-python

## 2. Polymorphism

**Polymorphism** is the ability of objects of different classes to be used interchangeably.

In Python, polymorphism can be achieved through:

1. _method overriding_
2. _method overloading._

In [2]:
# Define parent class Animal
class Animal:
    def type(self):
        print("animal")


# Define sub-class Dog	
class Dog(Animal):
    def type(self):
        print("dog")

# Initialize objects
obj_bear = Animal()
obj_terrier = Dog()

# Demonstrate method overriding
obj_bear.type()    # Returns animal
obj_terrier.type() # Returns dog

animal
dog


* **Function Polymorphism**

Certain functions in Python are polymorphic as well, meaning that they can act on multiple data types and structures to yield different kinds of information.

Python’s built-in len() function, for instance, can be used to return the length of an object. However, it will measure the length of the object differently depending on the object’s data type and structure. <br>
_For instance_, if the object is a string, the "len()" function will return the number of characters in the string. If the object is a list, it will return the number of entries in the list.

In [3]:
str1 = "animal"
print(len(str1))
# returns 6

list1 = ["giraffe","lion","bear","dog"]
print(len(list1))
# returns 4

6
4


_Example_: <br>
In Machine Learning, feature engineering is the process of creating new features from existing data that can improve the performance of a model. Polymorphism can be used to create a base class for feature engineering, and then create subclasses that implement specific feature engineering techniques such as scaling, normalization, or text processing.

In [4]:
# Import numpy for the data
import numpy as np


class FeatureEngineering:
    def transform(self, X):
        return X

class StandardScaler(FeatureEngineering):
    def transform(self, X):
        # Perform standard scaling on the input data
        return (X - X.mean()) / X.std()

class MinMaxScaler(FeatureEngineering):
    def transform(self, X):
        # Perform min-max scaling on the input data
        return (X - X.min()) / (X.max() - X.min())

# Define some data
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

fe = FeatureEngineering()
ss = StandardScaler()
mm = MinMaxScaler()

print(fe.transform(X))   # [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(ss.transform(X))   # [[-1.22474487, -1.22474487, -1.22474487],
                         #  [ 0.,          0.,          0.        ],
                         #  [ 1.22474487,  1.22474487,  1.22474487]]
print(mm.transform(X))   # [[ 0.,          0.,          0.        ],
                         #  [ 0.5,         0.5,         0.5       ],
                         #  [ 1.,          1.,          1.        ]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


By using polymorphism in Data Science and Machine Learning, you can write more modular and reusable code that is easier to maintain and extend. <br>
It also promotes the use of best practices and standards, which can improve collaboration and efficiency within a team.

**_Comparison_** <br>
In summary, inheritance is used to create new classes that are based on existing classes, while polymorphism is used to treat objects of different classes in a similar way.

https://www.educative.io/blog/what-is-polymorphism-python

## 3. Encapsulation

**Encapsulation** is the practice of hiding the internal details of a class from the outside world and exposing a public interface for interacting with the class. <br>
In Python, encapsulation can be achieved through the use of access modifiers like public, private (with _single_ underscore), and protected (with _double_ underscore).

It acts as a protective shield that puts restrictions on accessing variables and methods directly, and can prevent accidental or unauthorized modification of data.

In [5]:
class BankAccount:
    def __init__(self, account_number, balance):
        self.__account_number = account_number  # Cannot be accessed outside of class
        self.__balance = balance  # Cannot be accessed outside of class

    def get_balance(self):
        return self.__balance

    def deposit(self, amount):
        self.__balance += amount

    def withdraw(self, amount):
        if amount > self.__balance:
            raise ValueError("Insufficient balance")
        self.__balance -= amount

my_account = BankAccount("1234", 1000)
my_account.deposit(500)
my_account.withdraw(200)

print(my_account.get_balance()) # Output: 1300

1300


1. Encapsulation improves modularity: <br>
By encapsulating the internal details of an object, it becomes easier to change the implementation of the object without affecting the rest of the code. This allows for greater modularity, which can make the code easier to maintain and modify over time.

2. Encapsulation improves security: <br>
By controlling the access to an object's internal state, encapsulation can help prevent unintended or malicious modifications of the object. This can help improve the security and reliability of the code.

In summary, encapsulation is useful in machine learning for promoting modularity, protecting data privacy, improving code reuse, and helping with debugging. By encapsulating the different components of a model, you can make the code more maintainable, scalable, and easier to understand.

https://www.educative.io/answers/what-is-encapsulation-in-python

## 4. Decorators

**Decorator** is a special type of function that can modify or extend the behavior of another function or class.

A decorator function takes a function as an argument, performs some operation on it, and returns the modified function. <br>
The syntax for using a decorator is to prepend the function with the decorator function using the "@" symbol.

In [6]:
def log_decorator(func):
    def wrapper(*args, **kwargs):
        print("Calling function:", func.__name__)
        result = func(*args, **kwargs)
        return result
    return wrapper

@log_decorator
def add(a, b):
    return a + b

print(add(2, 3))

Calling function: add
5


_Benefits:_ <br>
Decorators are commonly used in Python for tasks like logging, performance monitoring, authentication, and caching. They can also be used to modify the behavior of classes and methods in addition to functions.